module.exports = {
  categories: [
    { slug: "all", label: "All" },
    { slug: "portrait", label: "Portrait" },
    { slug: "landscape", label: "Landscape" },
    { slug: "event", label: "Events" },
    { slug: "commercial", label: "Commercial" },
  ],
  items: [
    {
      title: "Editorial Portrait",
      image: "/assets/images/portfolio-1.jpg",
      category: "commercial",
      description: "Commercial",
    },
    {
      title: "Natural Portrait",
      image: "/assets/images/portfolio-2.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Mountain Light",
      image: "/assets/images/portfolio-3.jpg",
      category: "landscape",
      description: "Landscape",
    },
    {
      title: "Live Celebration",
      image: "/assets/images/portfolio-4.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Brand Story",
      image: "/assets/images/portfolio-5.jpg",
      category: "commercial",
      description: "Commercial",
    },
    {
      title: "Studio Session",
      image: "/assets/images/portfolio-6.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Open Horizon",
      image: "/assets/images/portfolio-7.jpg",
      category: "landscape",
      description: "Landscape",
    },
    {
      title: "Night Reception",
      image: "/assets/images/portfolio-8.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Product Hero",
      image: "/assets/images/portfolio-9.jpg",
      category: "commercial",
      description: "Commercial",
    },
    {
      title: "Confidence Portrait",
      image: "/assets/images/portfolio-10.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Golden Landscape",
      image: "/assets/images/portfolio-11.jpg",
      category: "landscape",
      description: "Landscape",
    },
    {
      title: "Wedding Highlights",
      image: "/assets/images/portfolio-12.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Outdoor Portrait Story",
      image: "/assets/images/blog-outdoor-portrait.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Wedding Dance Story",
      image: "/assets/images/blog-wedding-dance.jpg",
      category: "event",
      description: "Wedding",
    },
    {
      title: "Portrait Session 01",
      image: "/assets/images/portrait-photography-1.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 02",
      image: "/assets/images/portrait-photography-2.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 03",
      image: "/assets/images/portrait-photography-3.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 04",
      image: "/assets/images/portrait-photography-4.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 05",
      image: "/assets/images/portrait-photography-5.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 06",
      image: "/assets/images/portrait-photography-6.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 07",
      image: "/assets/images/portrait-photography-7.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 08",
      image: "/assets/images/portrait-photography-8.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Portrait Session 09",
      image: "/assets/images/portrait-photography-9.jpg",
      category: "portrait",
      description: "Portrait",
    },
    {
      title: "Event Coverage 01",
      image: "/assets/images/event-photography-1.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Event Coverage 02",
      image: "/assets/images/event-photography-2.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Event Coverage 03",
      image: "/assets/images/event-photography-3.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Event Coverage 04",
      image: "/assets/images/event-photography-4.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Event Coverage 05",
      image: "/assets/images/event-photography-5.jpg",
      category: "event",
      description: "Event",
    },
    {
      title: "Wedding Story 01",
      image: "/assets/images/wedding-photography-1.jpg",
      category: "event",
      description: "Wedding",
    },
    {
      title: "Wedding Story 02",
      image: "/assets/images/wedding-photography-2.jpg",
      category: "event",
      description: "Wedding",
    },
    {
      title: "Wedding Story 03",
      image: "/assets/images/wedding-photography-3.jpg",
      category: "event",
      description: "Wedding",
    },
    {
      title: "Wedding Story 04",
      image: "/assets/images/wedding-photography-4.jpg",
      category: "event",
      description: "Wedding",
    },
    {
      title: "Wedding Story 05",
      image: "/assets/images/wedding-photography-5.jpg",
      category: "event",
      description: "Wedding",
    },
  ],
};
